### ISSUE TITLE
"Failed to launch checking" on Warmup Maximum Pairwise Product Fixing... subtasks

### ISSUE THREAD

**Issue by alansegar** [jetbrains-academy/algo-challenges-in-kotlin#55]
Warmup `Sum of Two Digits` and `Maximum Pairwise Product` work as expected (`Check` button runs the tests and reports expected output).
But the following:
- `Maximum Pairwise Product -- Fixing the Integer Overflow Issue` 
- `Maximum Pairwise Product -- Fixing the Time Limit Issue`
result in `X Incorrect` `Failed to launch checking` despite `Peek Solution` showing that the code is identical to the solution.
It's not possible to see the error detail in the Course view, just:
```Failed to launch checking

Failed to launch checking

> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :util:compileKotlin UP-TO-DATE
> Task :util:compileJava NO-SOURCE
> Task :util:processResources NO-SOURCE
> Task :util:classes UP-TO-DATE
> Task :util:jar UP-TO-DATE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:compileKotlin UP-TO-DATE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:compileJava NO-SOURCE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:processResources NO-SOURCE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:classes UP-TO-DATE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:compileTestKotlin UP-TO-DATE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:compileTestJava NO-SOURCE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:processTestResources NO-SOURCE
> Task :Warmup-Maximum_Pairwise_Product_��Fixing_the_Integer_Overflow_Issue:testClasses UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 4s
6 actionable tasks: 6 up-to-date
```
but changing to the `Project` view shows the following in `build/reports/tests/test` 
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not execute test class 'Tests'.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:54)
	at java.base@21.0.2/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:119)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:66)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.gradle.internal.UncheckedException: java.lang.ClassNotFoundException: Tests
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:68)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.loadClass(JUnitPlatformTestClassProcessor.java:170)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.access$100(JUnitPlatformTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:104)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	... 16 more
Caused by: java.lang.ClassNotFoundException: Tests
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.loadClass(JUnitPlatformTestClassProcessor.java:168)
	... 21 more
```

Manually skipping ahead to `Queries and Incremental Updates - Count Ones` seems to allow progression through the course.

## Version details:

```
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  PythonCore (242.23339.11)
  com.jetbrains.space (242.23339.11)
  com.jetbrains.edu (2024.9-2024.2-1051)
  Error-prone plugin (242.20224.159)
  com.haulmont.jpab (242.22855.36)
Kotlin: 242.23339.11-IJ
```

**Comment by Geravant** [comment]
@DaniilBogdanovJB , please take a look at this
